name: Publish Site

on:
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  publish:
    name: Build & Deploy Quarto Project
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio_4.3.1_bioc_3.17:latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Staged dependencies
        uses: insightsengineering/staged-dependencies-action@v1
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: "."
          enable-check: false
          direction: upstream

      - name: Render Quarto Project
        run: quarto render --output-dir _site
        shell: bash

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
